### ISSUE TITLE
Is there a time when barcodes one application it is still on the menu bar, when using barcode -f it quits the application?

### ISSUE THREAD

**Issue by Jerry080801** [artginzburg/barhide#2]

**Comment by artginzburg** [comment]
Well, `barhide` restarts the app after changing the `NSStatusItem Visible Item-0` setting so that it takes effect.

If both `barhide` and `barhide --force` don't work, I think the app might be using a status item with a different index. Or the app explicitly changes the setting on startup.

Could you please tell me the app's name?

**Comment by Jerry080801** [comment]
One app would be "Google Drive“, and utools(https://u.tools/)

**Comment by artginzburg** [comment]
Just downloaded uTools to check that, and it turns out you need to quit the app and open it again so that it's hidden from the menu bar. Idk why but `barhide` cannot restart this particular app :)

**Comment by artginzburg** [comment]
****
